### PR TITLE
Create zengin-py

### PR DESCRIPTION
**Pull request by tell-k**
I've created python package and prepared to register PyPI(https://pypi.python.org/pypi).

Please feel free to review it.

You can try to regsiter PyPI.

１. Create pypi account
- https://pypi.python.org/pypi?%3Aaction=register_form

２. Upload package.

``` bash
$ git submodule update --init
$ git submodule foreach 'git pull origin master'
$ pip install -U pip setuptools wheel twine
$ python setup.py register
$ python setup.py release
$ twine upload dist/* -r pypi
```

３. You can confirm to uploaded to https://pypi.python.org/pypi/zengin_code/

see also [Tutorial on Packaging and Distributing Projects](https://packaging.python.org/en/latest/distributing.html)

If you want to deploy automatically using the CircleCI, 
You should set the enviroment values(PYPI_USERNAME, PYPI_PASSWORD) on CircleCI.

see also [bin/ci/deploy](https://github.com/tell-k/zengin-py/blob/master/bin/ci/deploy)

If you are busy. I'll register it instead of you. :)

thx.

### CODE REVIEW

**Comment by rosylilly** [comment]
Awesome! Thank you for pull request!

**Comment by tell-k** [comment]
@rosylilly 

Thank you for merging my pull request.
Sorry, my explanation was so bad.

https://pypi.python.org/pypi/zengin_code

The status of this package is registration only.
Next, you will need to upload the build packages to pypi.

Please try it, such as the following.

``` bash
# build package
$ python setup.py release
$ ls -la dist/
total 2952
-rw-rw-r--  1 tell_k  staff  1500624  5  2 18:09 zengin_code-1.0.0.20160417-py2.py3-none-any.whl
-rw-rw-r--  1 tell_k  staff     4182  5  2 18:09 zengin_code-1.0.0.20160417.tar.gz
# upload pacakges
$ twine upload dist/*
Uploading distributions to https://pypi.python.org/pypi
Uploading zengin_code-1.0.0.20160417-py2.py3-none-any.whl
Uploading zengin_code-1.0.0.20160417.tar.gz
```

If successful, you can see the following.
uploading success

thx

**Comment by rosylilly** [comment]
Oh, I missed. I've just upload package. thank you.

**Comment by tell-k** [comment]
👍  Thank you for the quick response.

**Pull request merged**
